// --- MOCK PASSWORD HASHING ---
// In a real app, use a library like bcrypt
const MOCK_PASSWORD_HASH = "$2b$10$fakerakefakerakefakerakeu3eP5wL3/URo2Z.Y5G.x3.g8T9u.1234"

// --- INTERFACES ---
export interface User {
  id: string
  email: string
  passwordHash: string
  role: "customer" | "individual_specialist" | "business_specialist"
  firstName?: string
  lastName?: string
  companyName?: string
  companyCode?: string
  createdAt: string
}

export interface SpecialistProfile {
  userId: string
  profession: string
  categories: string[] // Changed from category to categories (array)
  locations: string[] // Changed from location to locations (array)
  phone: string
  description: string
  services: string[]
  hourlyRate?: number
  experience?: number
  verified: boolean
  image: string
  type: "individual" | "business"
}

// --- PREDEFINED SERVICES ---
// Universal service categories for all specialists
export const serviceCategories = {
  "Automobiliai, transportas": [
    "Akumuliatoriai",
    "Autobusų, mikroautobusų nuoma",
    "Autokosmetika",
    "Automobilių dalys",
    "Automobilių garso ir apsaugos sistemos",
    "Automobilių nuoma",
    "Automobilių parkavimas",
    "Automobilių pervežimas",
    "Automobilių plovyklos",
    "Automobilių prekyba",
    "Automobilių remontas",
    "Automobilių stiklai",
    "Automobilių šaldymo įranga",
    "Automobilių techninė apžiūra",
    "Autosavartynas, naudotos dalys",
    "Autoservisai",
    "Autoservisų, plovyklų, degalinių įranga",
    "Dviračiai",
    "Dviračiai, paspirtukai",
    "Ekspedijavimas",
    "Geležinkelių transportas",
    "Logistikos paslaugos",
    "Motociklai",
    "Oro transportas, aviacija",
    "Padangos, ratlankiai",
    "Pagalba kelyje",
    "Sunkvežimių pardavimas, dalys, remontas",
    "Tepalai, alyvos",
    "Transporto paslaugos",
    "Vandens transportas",
  ],
  "Energetika, žaliavos, kuras": [
    "Antrines žaliavos",
    "Atliekų tvarkymas",
    "Energetika",
    "Gamtos apsauga",
    "Kuras šildymui, malkos, breket...",
    "Kuras, naftos produktai, degal...",
    "Metalų pardavimas, supirkimas",
    "Naudingosios iškasenos",
  ],
  "Finansai, teisė, draudimas": [
    "Antstoliai",
    "Apskaita",
    "Auditas",
    "Bankai, bankinės operacijos",
    "Buhalterinė apskaita",
    "Draudimas",
    "Finansai",
    "Greitieji kreditai, paskolos",
    "Investicinė veikla",
    "Konsultacijų paslaugos",
    "Notarų biurai",
    "Skolų išieškojimas",
    "Tarpininkavimas",
    "Teisinės paslaugos",
    "Teisėtvarka",
    "Turto vertinimas",
  ],
  "Kompiuteriai, IT technologijos": [
    "Interneto paslaugos",
    "Interneto svetainių kūrimas, tvarkymas",
    "Kompiuteriai ir programinė įranga",
    "Kompiuterių remontas, IT paslaugos",
    "Programinės įrangos kūrimas",
    "Telekomunikacijos, ryšio priemonės",
  ],
  "Laisvalaikis, pramogos, turizmas": [
    "Kaimo turizmas",
    "Kavinės, klubai, barai, restoranai",
    "Kelionės",
    "Kino paslaugos",
    "Kultūros centrai",
    "Muziejai",
    "Pirtys ir baseinai",
    "Poilsio namai, sanatorijos",
    "Pramogos ir poilsis",
    "Renginių organizavimas",
    "Sporto paslaugos, sporto klubai",
    "Sveikatingumo, SPA centrai",
    "Teatrai",
    "Viešbučiai, moteliai",
  ],
  "Maisto produktai, gėrimai, prekyba": [
    "Gėrimai (alkoholiniai)",
    "Gėrimai (nealkoholiniai)",
    "Kava, arbata",
    "Kepyklos",
    "Konditerija, saldumynai",
    "Maisto gamyba",
    "Maisto parduotuvės",
    "Maisto produktai",
    "Mėsos perdirbimas, mėsos produktai",
    "Naminiai gyvūnai, maistas, reikmenys",
    "Pienas, pieno produktai",
    "Šaldyti maisto produktai",
    "Šviežį produktai",
  ],
  "Medicina, sveikata, farmacija": [
    "Akušeriai, ginekologai",
    "Estetinė medicina",
    "Globos, rūpybos įstaigos, socialiniai darbuotojai",
    "Greitoji medicinos pagalba",
    "Medicininė įranga",
    "Medicininiai tyrimai, laboratorijos",
    "Medicinos įstaigos",
    "Odontologija, paslaugos",
    "Optika, akiniai",
    "Plastinė, estetinė chirurgija",
    "Privačios gydymo įstaigos",
    "Psichologai, psichoterapeutai",
    "Sanatorijos, reabilitacijos centrai",
    "Vaistai, medicinos medžiagos",
    "Veterinarija",
    "Visuomenės sveikatos priežiūra",
  ],
  "Paslaugos": [
    "Apsaugos sistemos, prietaisai",
    "Apželdimimas ir aplinkos tvarkymas",
    "Avarinės tarnybos",
    "Butities paslaugos",
    "Darbo paieška, tarpinimas",
    "Darbo sauga",
    "Drabužinės",
    "Fotografijos paslaugos, įranga",
    "Grožio salonai, kirpyklos",
    "Imonių steigimas",
    "Individuali veikla",
    "Informacijos teikimas",
    "Keleivių pervežimas",
    "Kenkėjų naikinimas, dezinfekcija",
    "Kita veikla",
    "Komunalinės paslaugos",
    "Laidojimo paslaugos, kremavimas",
    "Laikrodžiai",
    "Lombardi",
    "Maistas į namus, biurą",
    "Paminklai, antkapiai, kapų priežiūra",
    "Parodos, mugės",
    "Paštų administravimas",
    "Patalpų nuoma",
    "Patentinės paslaugos",
    "Perkraustymas",
    "Personalo atranka",
    "Priesagarine sauga, sistemos",
    "Reklamos paslaugos",
    "Saugos tarnybos",
    "Siuvimas, medžiagos",
    "Švaros, valymo paslaugos",
    "Taksi paslaugos",
    "Tarpininkavimas",
    "Vertimas",
    "Vertimo paslaugos",
    "Vestuviniai drabužiai",
    "Video ir audio aparatūra, paslaugos",
    "Video ir audio įrašai",
  ],
  "Pramonė, gamyba, įranga": [
    "Automatizavimas, automatika",
    "Baldai (gamyba)",
    "Chemijos pramonė, gaminiai",
    "Dujos, dujų įranga",
    "Elektros dalys ir įranga",
    "Elektros varikliai",
    "Gamyba",
    "Guoliai",
    "Hidraulika, pneumatika",
    "Kompresoriai, siurbliai",
    "Komunalinė technika",
    "Krautuvai, keltuvai, liftai",
    "Laboratorijos įranga",
    "Laivų remontas, statyba",
    "Maisto gamybos ir perdirbimo įranga",
    "Matavimo prietaisai",
    "Medienos apdirbimas, gaminiai",
    "Metalo apdirbimas, gaminiai",
    "Metalo konstrukcijos, aparatai",
    "Plastikai, guma, jų gaminiai",
    "Plovyklų, autoservisų, degalinių įranga",
    "Pramonės įrengimai",
    "Prekybos įranga",
    "Restoranų, kavinių, barų įranga",
    "Sandėliavimas",
    "Sertifikavimo paslaugos",
    "Šildymas, įrenginiai",
    "Suvirinimas ir suvirinimo aparatūra",
    "Tara, pakuotės",
    "Technologinė įranga",
    "Tyrimai, ekspertizės",
  ],
  "Prekės, prekyba": [
    "Apranga, drabužiai",
    "Audinio, patalynė",
    "Avalynė, batai",
    "Avarinės tarnybos",
    "Baldai (prekyba)",
    "Baldų gamybos medžiagos, furnitūra",
    "Biuro įranga",
    "Buitinė technika",
    "Darbo apranga",
    "Didmeninė prekyba",
    "Dovanos",
    "Durys, raktai, spynos",
    "Eksportas",
    "Elektros montavimo medžiagos",
    "Fejerverkai, pirotechnika",
    "Galanerija, tekstilė",
    "Gėlės ir dekoratyviniai augalai",
    "Ginklai, savisaugos priemonės",
    "Higienos reikmenys",
    "Importas",
    "Indai, valymo įrankiai",
    "Interneto parduotuvės",
    "Juvelyriniai dirbiniai ir bižuterija",
    "Kailiai ir jų dirbiniai",
    "Kanceliarijos prekės",
    "Keramikos gaminiai",
    "Kosmetika, parfumerija",
    "Mažmeninė prekyba",
    "Meno salonai ir galerijos, dailės reikmenys",
    "Muzikos instrumentai",
    "Odos apdirbimas, gaminiai",
    "Pardavimo automatai",
    "Popierius, jo gaminiai",
    "Priesagrinė sauga, sistemos",
    "Sendaikčiai, antikvariatas",
    "Sporto, turizmo reikmenys",
    "Stiklas ir jo gaminiai",
    "Sviesos sistemos, šviestuvai",
    "Tabakas",
    "Tabako gaminiai",
    "Turgavietės",
    "Ūkio prekės",
    "Vaikų prekės",
    "Vaizdo stebėjimo sistemos",
    "Valymo priemonės",
    "Vestuviniai drabužiai",
    "Žaislai",
    "Žaliuzės, užuolaidos, roletai",
    "Žūklės ir medžioklės reikmenys",
  ],
  "Reklama, leidyba": [
    "Grafika, dizainas",
    "Reklamos paslaugos",
    "SEO paslaugos",
    "Spauda, laikraščiai, žurnalai",
    "Spaustuves, leidyba",
    "Televizija ir radijas",
  ],
  "Statyba, remontas, medžiagos, NT": [
    "Akmens gaminiai",
    "Architektai",
    "Aukštalpių paslaugos",
    "Betonas ir jo gaminiai",
    "Dažai, lakai",
    "Elektros instaliacijos darbai",
    "Fasadas, fasado apdaila",
    "Geodezija, kartografija",
    "Geologija",
    "Grindys, grindų dangos",
    "Griovimas, grėžimas",
    "Inžineriniai tinklai ir sistemos",
    "Interjero apdailos medžiagos",
    "Įrankiai",
    "Kelių tiesimas, remontas, tiltas",
    "Langai, durys",
    "Mediena, jos gaminiai",
    "Melioracija, melioracijos technika",
    "Namų statyba",
    "Nekilnojamasis turtas",
    "Patalpų nuoma",
    "Projektavimas",
    "Santechnika",
    "Sienos, lubos",
    "Šildymas, įrenginiai",
    "Šiltinimas, renovacija",
    "Statyba",
    "Statybinės medžiagos",
    "Statyba, renovacija",
    "Statybos technika, įranga, nuoma",
    "Stogų dangos, paslaugos",
    "Tvirtinimo detalės, elementai",
    "Vandentiekis, nuotekos, vamzdynai",
    "Vartai, tvoros",
    "Ventiliacija, kondicionavimas",
    "Žemetvarka",
    "Židiniai, krosnys",
  ],
  "Švietimas, ugdymas, kultūra": [
    "Aukštosios mokyklos, universitetas",
    "Bibliotekos, archyvavimo paslaugos",
    "Institutai, moksliniai tyrimai",
    "Kalbų kursai",
    "Knygos ir knygynai",
    "Meno mokymo įstaigos",
    "Mokyklos, gimnazijos",
    "Mokymo centrai, kursai",
    "Mokymo kursai",
    "Profesinio mokymo įstaigos",
    "Vaikų būreliai",
    "Vaikų darželiai",
    "Vairavimo mokymas",
  ],
  "Valstybinės įstaigos, organizacijos": [
    "Bendruomenės",
    "Globa ir priežiūra",
    "Gyvūnų globa",
    "Kontrolės tarnybos",
    "Labdara, parama",
    "Muitinių paslaugos, muitinės",
    "Namų savininkų bendrijos",
    "Politinės organizacijos",
    "Religinės organizacijos",
    "Savivaldybės",
    "Sąjungos, fondai, asociacijos",
    "Seimynos",
    "Senūnijos",
    "Socialinės paslaugos",
    "Sodininkų bendrijos",
    "Sporto organizacijos",
    "Valstybinės institucijos",
  ],
  "Žemės ūkis, agrotechnika": [
    "Augalininkystė, sodininkystė",
    "Daržininkystė, sodininkystė",
    "Grūdininkystė",
    "Gyvulininkystė, veislininkystė",
    "Miškininkystė",
    "Miško gėrybės",
    "Miško, sodo, vejos technika",
    "Pašarai, gyvulinis maistas",
    "Trąšos",
    "Vaisiai",
    "Žemes ūkio technika",
    "Žemės ūkis, paslaugos",
    "Žuvininkystė",
    "Žuvininkystė, žuvies produktai",
    "Žverininkystė",
  ],
}

// Export predefinedServices as an alias for serviceCategories
export const predefinedServices = serviceCategories

// Default cities
const defaultCities = [
  "Vilnius",
  "Kaunas",
  "Klaipėda",
  "Šiauliai",
  "Panevėžys",
  "Alytus",
  "Marijampolė",
  "Mažeikiai",
  "Jonava",
  "Utena",
]

// --- MOCK DATABASE ---
const users: User[] = [
  {
    id: "user_1",
    email: "customer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "customer",
    firstName: "Petras",
    lastName: "Klientauskas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_2",
    email: "individual@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Gintarė",
    lastName: "Urbonaitė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_3",
    email: "business@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Petraičio Santechnika MB",
    companyCode: "305123456",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_4",
    email: "programmer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Tomas",
    lastName: "Programauskas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_5",
    email: "itcompany@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "TechSolutions UAB",
    companyCode: "305987654",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_6",
    email: "photographer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Laura",
    lastName: "Fotografė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_7",
    email: "accountant@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Rasa",
    lastName: "Skaičiuotoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_8",
    email: "cleaning@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Švarūs Namai MB",
    companyCode: "305456789",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_9",
    email: "teacher@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Ingrida",
    lastName: "Mokytoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_10",
    email: "massage@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Vida",
    lastName: "Masažuotoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_11",
    email: "restaurant@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Skanus Maistas UAB",
    companyCode: "305123789",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_12",
    email: "lawyer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Mindaugas",
    lastName: "Teisininkas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_13",
    email: "trainer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Eglė",
    lastName: "Trenerė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_14",
    email: "gintpazn@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Agrovartai, UAB",
    companyCode: "305000014",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_15",
    email: "info@absautoservisas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ABS AUTOSERVISAS, UAB",
    companyCode: "305000015",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_16",
    email: "info@acura.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Acura, UAB",
    companyCode: "305000016",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_17",
    email: "ajelectronics1@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AJ Electronics, UAB",
    companyCode: "305000017",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_18",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000018",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_19",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000019",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_20",
    email: "aswobaltic@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ASWO Baltic, UAB",
    companyCode: "305000020",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_21",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000021",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_22",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000022",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_23",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000023",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_24",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000024",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_25",
    email: "gintaras@autoga.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoga, UAB",
    companyCode: "305000025",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_26",
    email: "autolora@autolora.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autolora, UAB",
    companyCode: "305000026",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_27",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000027",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_28",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000028",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_29",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000029",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_30",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000030",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_31",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000031",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_32",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000032",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_33",
    email: "gintpazn@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Agrovartai, UAB",
    companyCode: "305000033",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_34",
    email: "info@absautoservisas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ABS AUTOSERVISAS, UAB",
    companyCode: "305000034",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_35",
    email: "info@acura.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Acura, UAB",
    companyCode: "305000035",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_36",
    email: "ajelectronics1@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AJ Electronics, UAB",
    companyCode: "305000036",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_37",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000037",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_38",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000038",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_39",
    email: "aswobaltic@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ASWO Baltic, UAB",
    companyCode: "305000039",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_40",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000040",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_41",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000041",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_42",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000042",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_43",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000043",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_44",
    email: "gintaras@autoga.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoga, UAB",
    companyCode: "305000044",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_45",
    email: "autolora@autolora.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autolora, UAB",
    companyCode: "305000045",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_27",
    email: "labas@smartrent.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aušra kelyje, MB",
    companyCode: "305000027",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_28",
    email: "info@atntravel.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Mikroautobusų nuoma Vilniuje, UAB",
    companyCode: "305000028",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_29",
    email: "info@uzuojauta.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Užuojauta, UAB",
    companyCode: "305000029",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_30",
    email: "sigis@kaunas.omnitel.net",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "A ir S, kelionių agentūra, S. Jasinskio komercijos įmonė",
    companyCode: "305000030",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_31",
    email: "a9vilnius@b4net.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "A9 Vilnius, UAB",
    companyCode: "305000031",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_32",
    email: "vezipats@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aeromobilis, UAB",
    companyCode: "305000032",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_33",
    email: "aidarent@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AIDA Rent, UAB",
    companyCode: "305000033",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_34",
    email: "info@aldova.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aldova, UAB",
    companyCode: "305000034",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_35",
    email: "info@aautobusai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Algimanto autobusai, UAB",
    companyCode: "305000035",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_36",
    email: "alrodis.uab@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alrodis, UAB",
    companyCode: "305000036",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_37",
    email: "info@alvaturas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alvaturas, UAB",
    companyCode: "305000037",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_38",
    email: "amziausvartai@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AMŽIAUS VARTAI, UAB",
    companyCode: "305000038",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_39",
    email: "info@arselina.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Arselina, UAB",
    companyCode: "305000039",
    createdAt: new Date().toISOString(),
  },
]

const specialistProfiles: SpecialistProfile[] = [
  // Akumuliatorių įmonės
  {
    userId: "user_14",
    type: "business",
    profession: "Automobilių akumuliatoriai",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000001",
    description: "Agrovartai, UAB - automobilių akumuliatorių pardavimas ir aptarnavimas Kauno rajone.",
    services: ["Akumuliatoriai"],
    hourlyRate: 35,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_15",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000002",
    description: "ABS AUTOSERVISAS, UAB - profesionalus automobilių servisas su akumuliatorių paslaugomis Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_16",
    type: "business",
    profession: "Automobilių elektronika",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000003",
    description: "Acura, UAB - automobilių elektronikos ir akumuliatorių specialistai Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 45,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_17",
    type: "business",
    profession: "Automobilių elektronika",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37037000004",
    description: "AJ Electronics, UAB - automobilių elektronikos sprendimai ir akumuliatoriai Rokiškyje/Panevėžyje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 42,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_18",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000005",
    description: "AKSTĖ-servisas, UAB - pilnas automobilių aptarnavimas su akumuliatorių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 38,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_19",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37037000006",
    description: "ARV SERVICE, UAB - automobilių servisas specializuojantis akumuliatorių srityje Panevėžyje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 36,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_20",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000007",
    description: "ASWO Baltic, UAB - Baltijos šalių automobilių servisas su akumuliatorių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_21",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000008",
    description: "Ausegra, UAB - automobilių dalių pardavimas ir akumuliatorių aptarnavimas Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 33,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_22",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000009",
    description: "Auto Aves, UAB - automobilių servisas su akumuliatorių ir dalių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 37,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_23",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000010",
    description: "Autoaibė, UAB - automobilių servisas specializuojantis akumuliatorių srityje Klaipėdoje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 39,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_24",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000011",
    description: "Autodalykai, MB - automobilių servisas su akumuliatorių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 34,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_25",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000012",
    description: "Autoga, UAB - automobilių servisas su akumuliatorių paslaugomis Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 41,
    experience: 13,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_26",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000013",
    description: "Autolora, UAB - automobilių servisas su akumuliatorių paslaugomis Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  // Autobusų ir mikroautobusų nuomos įmonės
  {
    userId: "user_27",
    type: "business",
    profession: "Mikroautobusų nuoma",
    categories: ["Automobiliai, transportas"],
    locations: ["Šiauliai"], // Telšių r. -> Šiauliai apskritis
    phone: "+37037000027",
    description: "Aušra kelyje, MB - mikroautobusų nuomos paslaugos Telšių rajone.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 45,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_28",
    type: "business",
    profession: "Mikroautobusų nuoma",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000028",
    description: "Mikroautobusų nuoma Vilniuje, UAB - mikroautobusų nuomos paslaugos Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 40,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_29",
    type: "business",
    profession: "Laidojimo paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000029",
    description: "Užuojauta, UAB - laidojimo paslaugos ir transporto organizavimas Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 42,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_30",
    type: "business",
    profession: "Kelionių organizavimas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000030",
    description: "A ir S, kelionių agentūra - kelionių organizavimas ir autobusų nuoma Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 38,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_31",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000031",
    description: "A9 Vilnius, UAB - transporto paslaugos ir autobusų nuoma Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 44,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_32",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000032",
    description: "Aeromobilis, UAB - transporto paslaugos ir mikroautobusų nuoma Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 41,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_33",
    type: "business",
    profession: "Automobilių nuoma",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000033",
    description: "AIDA Rent, UAB - automobilių ir mikroautobusų nuomos paslaugos Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 39,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_34",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000034",
    description: "Aldova, UAB - transporto paslaugos ir autobusų nuoma Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 43,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_35",
    type: "business",
    profession: "Autobusų paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000035",
    description: "Algimanto autobusai, UAB - autobusų nuomos paslaugos Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 46,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_36",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Alytus"],
    phone: "+37037000036",
    description: "Alrodis, UAB - transporto paslaugos ir autobusų nuoma Alytuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 37,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_37",
    type: "business",
    profession: "Turizmo paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000037",
    description: "Alvaturas, UAB - turizmo paslaugos ir autobusų nuoma Neringoje/Klaipėdoje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 48,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_38",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000038",
    description: "AMŽIAUS VARTAI, UAB - transporto paslaugos ir autobusų nuoma Klaipėdoje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 40,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_39",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Jonava"],
    phone: "+37037000039",
    description: "Arselina, UAB - transporto paslaugos ir mikroautobusų nuoma Jonavoje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 36,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
]

// --- DATABASE ACCESS LAYER ---
export const db = {
  users: {
    async findByEmail(email: string): Promise<User | undefined> {
      return users.find((u) => u.email.toLowerCase() === email.toLowerCase())
    },
    async create(data: Omit<User, "id" | "createdAt" | "passwordHash"> & { password?: string }): Promise<User> {
      const newUser: User = {
        id: `user_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        ...data,
        passwordHash: MOCK_PASSWORD_HASH, // In real app: await bcrypt.hash(data.password, 10)
        createdAt: new Date().toISOString(),
      }
      users.push(newUser)
      return newUser
    },
  },
  specialists: {
    async getAll() {
      // Join user and specialist data
      return specialistProfiles.map((profile) => {
        const user = users.find((u) => u.id === profile.userId)
        return {
          ...profile,
          email: user?.email,
          firstName: user?.firstName,
          lastName: user?.lastName,
          companyName: user?.companyName,
          companyCode: user?.companyCode,
        }
      })
    },
    async createProfile(
      data: Omit<SpecialistProfile, "verified" | "image" | "hourlyRate" | "experience">,
    ): Promise<SpecialistProfile> {
      const newProfile: SpecialistProfile = {
        ...data,
        hourlyRate: 25, // Default hourly rate
        experience: 1, // Default experience
        verified: false, // Verification would be a separate process
        image: "/placeholder.svg?height=200&width=200",
      }
      specialistProfiles.push(newProfile)
      return newProfile
    },
    async updateProfile(userId: string, updates: Partial<SpecialistProfile>): Promise<SpecialistProfile | null> {
      const profileIndex = specialistProfiles.findIndex((p) => p.userId === userId)
      if (profileIndex === -1) return null

      specialistProfiles[profileIndex] = { ...specialistProfiles[profileIndex], ...updates }
      return specialistProfiles[profileIndex]
    },
    async getByUserId(userId: string): Promise<SpecialistProfile | undefined> {
      return specialistProfiles.find((p) => p.userId === userId)
    },
  },
  // Mock password comparison
  async comparePassword(password: string, hash: string): Promise<boolean> {
    // In a real app: return await bcrypt.compare(password, hash)
    return password.length > 0 && hash === MOCK_PASSWORD_HASH
  },
}

// This is the type that will be returned from the joined query
export type FullSpecialistProfile = Awaited<ReturnType<typeof db.specialists.getAll>>[0]