// --- MOCK PASSWORD HASHING ---
// In a real app, use a library like bcrypt
const MOCK_PASSWORD_HASH = "$2b$10$fakerakefakerakefakerakeu3eP5wL3/URo2Z.Y5G.x3.g8T9u.1234"

// --- INTERFACES ---
export interface User {
  id: string
  email: string
  passwordHash: string
  role: "customer" | "individual_specialist" | "business_specialist"
  firstName?: string
  lastName?: string
  companyName?: string
  companyCode?: string
  createdAt: string
}

export interface SpecialistProfile {
  userId: string
  profession: string
  categories: string[] // Changed from category to categories (array)
  locations: string[] // Changed from location to locations (array)
  phone: string
  description: string
  services: string[]
  hourlyRate?: number
  experience?: number
  verified: boolean
  image: string
  type: "individual" | "business"
}

// --- PREDEFINED SERVICES ---
// Universal service categories for all specialists
export const serviceCategories = {
  "Automobiliai, transportas": [
    "Akumuliatoriai",
    "Autobusų, mikroautobusų nuoma",
    "Autokosmetika",
    "Automobilių dalys",
    "Automobilių garso ir apsaugos sistemos",
    "Automobilių nuoma",
    "Automobilių parkavimas",
    "Automobilių pervežimas",
    "Automobilių plovyklos",
    "Automobilių prekyba",
    "Automobilių remontas",
    "Automobilių stiklai",
    "Automobilių šaldymo įranga",
    "Automobilių techninė apžiūra",
    "Autosavartynas, naudotos dalys",
    "Autoservisai",
    "Autoservisų, plovyklų, degalinių įranga",
    "Dviračiai",
    "Dviračiai, paspirtukai",
    "Ekspedijavimas",
    "Geležinkelių transportas",
    "Logistikos paslaugos",
    "Motociklai",
    "Oro transportas, aviacija",
    "Padangos, ratlankiai",
    "Pagalba kelyje",
    "Sunkvežimių pardavimas, dalys, remontas",
    "Tepalai, alyvos",
    "Transporto paslaugos",
    "Vandens transportas",
  ],
  "Energetika, žaliavos, kuras": [
    "Antrines žaliavos",
    "Atliekų tvarkymas",
    "Energetika",
    "Gamtos apsauga",
    "Kuras šildymui, malkos, breket...",
    "Kuras, naftos produktai, degal...",
    "Metalų pardavimas, supirkimas",
    "Naudingosios iškasenos",
  ],
  "Finansai, teisė, draudimas": [
    "Antstoliai",
    "Apskaita",
    "Auditas",
    "Bankai, bankinės operacijos",
    "Buhalterinė apskaita",
    "Draudimas",
    "Finansai",
    "Greitieji kreditai, paskolos",
    "Investicinė veikla",
    "Konsultacijų paslaugos",
    "Notarų biurai",
    "Skolų išieškojimas",
    "Tarpininkavimas",
    "Teisinės paslaugos",
    "Teisėtvarka",
    "Turto vertinimas",
  ],
  "Kompiuteriai, IT technologijos": [
    "Interneto paslaugos",
    "Interneto svetainių kūrimas, tvarkymas",
    "Kompiuteriai ir programinė įranga",
    "Kompiuterių remontas, IT paslaugos",
    "Programinės įrangos kūrimas",
    "Telekomunikacijos, ryšio priemonės",
  ],
  "Laisvalaikis, pramogos, turizmas": [
    "Kaimo turizmas",
    "Kavinės, klubai, barai, restoranai",
    "Kelionės",
    "Kino paslaugos",
    "Kultūros centrai",
    "Muziejai",
    "Pirtys ir baseinai",
    "Poilsio namai, sanatorijos",
    "Pramogos ir poilsis",
    "Renginių organizavimas",
    "Sporto paslaugos, sporto klubai",
    "Sveikatingumo, SPA centrai",
    "Teatrai",
    "Viešbučiai, moteliai",
  ],
  "Maisto produktai, gėrimai, prekyba": [
    "Gėrimai (alkoholiniai)",
    "Gėrimai (nealkoholiniai)",
    "Kava, arbata",
    "Kepyklos",
    "Konditerija, saldumynai",
    "Maisto gamyba",
    "Maisto parduotuvės",
    "Maisto produktai",
    "Mėsos perdirbimas, mėsos produktai",
    "Naminiai gyvūnai, maistas, reikmenys",
    "Pienas, pieno produktai",
    "Šaldyti maisto produktai",
    "Šviežį produktai",
  ],
  "Medicina, sveikata, farmacija": [
    "Akušeriai, ginekologai",
    "Estetinė medicina",
    "Globos, rūpybos įstaigos, socialiniai darbuotojai",
    "Greitoji medicinos pagalba",
    "Medicininė įranga",
    "Medicininiai tyrimai, laboratorijos",
    "Medicinos įstaigos",
    "Odontologija, paslaugos",
    "Optika, akiniai",
    "Plastinė, estetinė chirurgija",
    "Privačios gydymo įstaigos",
    "Psichologai, psichoterapeutai",
    "Sanatorijos, reabilitacijos centrai",
    "Vaistai, medicinos medžiagos",
    "Veterinarija",
    "Visuomenės sveikatos priežiūra",
  ],
  "Paslaugos": [
    "Apsaugos sistemos, prietaisai",
    "Apželdimimas ir aplinkos tvarkymas",
    "Avarinės tarnybos",
    "Butities paslaugos",
    "Darbo paieška, tarpinimas",
    "Darbo sauga",
    "Drabužinės",
    "Fotografijos paslaugos, įranga",
    "Grožio salonai, kirpyklos",
    "Imonių steigimas",
    "Individuali veikla",
    "Informacijos teikimas",
    "Keleivių pervežimas",
    "Kenkėjų naikinimas, dezinfekcija",
    "Kita veikla",
    "Komunalinės paslaugos",
    "Laidojimo paslaugos, kremavimas",
    "Laikrodžiai",
    "Lombardi",
    "Maistas į namus, biurą",
    "Paminklai, antkapiai, kapų priežiūra",
    "Parodos, mugės",
    "Paštų administravimas",
    "Patalpų nuoma",
    "Patentinės paslaugos",
    "Perkraustymas",
    "Personalo atranka",
    "Priesagarine sauga, sistemos",
    "Reklamos paslaugos",
    "Saugos tarnybos",
    "Siuvimas, medžiagos",
    "Švaros, valymo paslaugos",
    "Taksi paslaugos",
    "Tarpininkavimas",
    "Vertimas",
    "Vertimo paslaugos",
    "Vestuviniai drabužiai",
    "Video ir audio aparatūra, paslaugos",
    "Video ir audio įrašai",
  ],
  "Pramonė, gamyba, įranga": [
    "Automatizavimas, automatika",
    "Baldai (gamyba)",
    "Chemijos pramonė, gaminiai",
    "Dujos, dujų įranga",
    "Elektros dalys ir įranga",
    "Elektros varikliai",
    "Gamyba",
    "Guoliai",
    "Hidraulika, pneumatika",
    "Kompresoriai, siurbliai",
    "Komunalinė technika",
    "Krautuvai, keltuvai, liftai",
    "Laboratorijos įranga",
    "Laivų remontas, statyba",
    "Maisto gamybos ir perdirbimo įranga",
    "Matavimo prietaisai",
    "Medienos apdirbimas, gaminiai",
    "Metalo apdirbimas, gaminiai",
    "Metalo konstrukcijos, aparatai",
    "Plastikai, guma, jų gaminiai",
    "Plovyklų, autoservisų, degalinių įranga",
    "Pramonės įrengimai",
    "Prekybos įranga",
    "Restoranų, kavinių, barų įranga",
    "Sandėliavimas",
    "Sertifikavimo paslaugos",
    "Šildymas, įrenginiai",
    "Suvirinimas ir suvirinimo aparatūra",
    "Tara, pakuotės",
    "Technologinė įranga",
    "Tyrimai, ekspertizės",
  ],
  "Prekės, prekyba": [
    "Apranga, drabužiai",
    "Audinio, patalynė",
    "Avalynė, batai",
    "Avarinės tarnybos",
    "Baldai (prekyba)",
    "Baldų gamybos medžiagos, furnitūra",
    "Biuro įranga",
    "Buitinė technika",
    "Darbo apranga",
    "Didmeninė prekyba",
    "Dovanos",
    "Durys, raktai, spynos",
    "Eksportas",
    "Elektros montavimo medžiagos",
    "Fejerverkai, pirotechnika",
    "Galanerija, tekstilė",
    "Gėlės ir dekoratyviniai augalai",
    "Ginklai, savisaugos priemonės",
    "Higienos reikmenys",
    "Importas",
    "Indai, valymo įrankiai",
    "Interneto parduotuvės",
    "Juvelyriniai dirbiniai ir bižuterija",
    "Kailiai ir jų dirbiniai",
    "Kanceliarijos prekės",
    "Keramikos gaminiai",
    "Kosmetika, parfumerija",
    "Mažmeninė prekyba",
    "Meno salonai ir galerijos, dailės reikmenys",
    "Muzikos instrumentai",
    "Odos apdirbimas, gaminiai",
    "Pardavimo automatai",
    "Popierius, jo gaminiai",
    "Priesagrinė sauga, sistemos",
    "Sendaikčiai, antikvariatas",
    "Sporto, turizmo reikmenys",
    "Stiklas ir jo gaminiai",
    "Sviesos sistemos, šviestuvai",
    "Tabakas",
    "Tabako gaminiai",
    "Turgavietės",
    "Ūkio prekės",
    "Vaikų prekės",
    "Vaizdo stebėjimo sistemos",
    "Valymo priemonės",
    "Vestuviniai drabužiai",
    "Žaislai",
    "Žaliuzės, užuolaidos, roletai",
    "Žūklės ir medžioklės reikmenys",
  ],
  "Reklama, leidyba": [
    "Grafika, dizainas",
    "Reklamos paslaugos",
    "SEO paslaugos",
    "Spauda, laikraščiai, žurnalai",
    "Spaustuves, leidyba",
    "Televizija ir radijas",
  ],
  "Statyba, remontas, medžiagos, NT": [
    "Akmens gaminiai",
    "Architektai",
    "Aukštalpių paslaugos",
    "Betonas ir jo gaminiai",
    "Dažai, lakai",
    "Elektros instaliacijos darbai",
    "Fasadas, fasado apdaila",
    "Geodezija, kartografija",
    "Geologija",
    "Grindys, grindų dangos",
    "Griovimas, grėžimas",
    "Inžineriniai tinklai ir sistemos",
    "Interjero apdailos medžiagos",
    "Įrankiai",
    "Kelių tiesimas, remontas, tiltas",
    "Langai, durys",
    "Mediena, jos gaminiai",
    "Melioracija, melioracijos technika",
    "Namų statyba",
    "Nekilnojamasis turtas",
    "Patalpų nuoma",
    "Projektavimas",
    "Santechnika",
    "Sienos, lubos",
    "Šildymas, įrenginiai",
    "Šiltinimas, renovacija",
    "Statyba",
    "Statybinės medžiagos",
    "Statyba, renovacija",
    "Statybos technika, įranga, nuoma",
    "Stogų dangos, paslaugos",
    "Tvirtinimo detalės, elementai",
    "Vandentiekis, nuotekos, vamzdynai",
    "Vartai, tvoros",
    "Ventiliacija, kondicionavimas",
    "Žemetvarka",
    "Židiniai, krosnys",
  ],
  "Švietimas, ugdymas, kultūra": [
    "Aukštosios mokyklos, universitetas",
    "Bibliotekos, archyvavimo paslaugos",
    "Institutai, moksliniai tyrimai",
    "Kalbų kursai",
    "Knygos ir knygynai",
    "Meno mokymo įstaigos",
    "Mokyklos, gimnazijos",
    "Mokymo centrai, kursai",
    "Mokymo kursai",
    "Profesinio mokymo įstaigos",
    "Vaikų būreliai",
    "Vaikų darželiai",
    "Vairavimo mokymas",
  ],
  "Valstybinės įstaigos, organizacijos": [
    "Bendruomenės",
    "Globa ir priežiūra",
    "Gyvūnų globa",
    "Kontrolės tarnybos",
    "Labdara, parama",
    "Muitinių paslaugos, muitinės",
    "Namų savininkų bendrijos",
    "Politinės organizacijos",
    "Religinės organizacijos",
    "Savivaldybės",
    "Sąjungos, fondai, asociacijos",
    "Seimynos",
    "Senūnijos",
    "Socialinės paslaugos",
    "Sodininkų bendrijos",
    "Sporto organizacijos",
    "Valstybinės institucijos",
  ],
  "Žemės ūkis, agrotechnika": [
    "Augalininkystė, sodininkystė",
    "Daržininkystė, sodininkystė",
    "Grūdininkystė",
    "Gyvulininkystė, veislininkystė",
    "Miškininkystė",
    "Miško gėrybės",
    "Miško, sodo, vejos technika",
    "Pašarai, gyvulinis maistas",
    "Trąšos",
    "Vaisiai",
    "Žemes ūkio technika",
    "Žemės ūkis, paslaugos",
    "Žuvininkystė",
    "Žuvininkystė, žuvies produktai",
    "Žverininkystė",
  ],
}

// Export predefinedServices as an alias for serviceCategories
export const predefinedServices = serviceCategories

// Default cities
const defaultCities = [
  "Vilnius",
  "Kaunas",
  "Klaipėda",
  "Šiauliai",
  "Panevėžys",
  "Alytus",
  "Marijampolė",
  "Mažeikiai",
  "Jonava",
  "Utena",
]

// --- MOCK DATABASE ---
const users: User[] = [
  {
    id: "user_1",
    email: "customer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "customer",
    firstName: "Petras",
    lastName: "Klientauskas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_2",
    email: "individual@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Gintarė",
    lastName: "Urbonaitė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_3",
    email: "business@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Petraičio Santechnika MB",
    companyCode: "305123456",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_4",
    email: "programmer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Tomas",
    lastName: "Programauskas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_5",
    email: "itcompany@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "TechSolutions UAB",
    companyCode: "305987654",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_6",
    email: "photographer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Laura",
    lastName: "Fotografė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_7",
    email: "accountant@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Rasa",
    lastName: "Skaičiuotoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_8",
    email: "cleaning@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Švarūs Namai MB",
    companyCode: "305456789",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_9",
    email: "teacher@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Ingrida",
    lastName: "Mokytoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_10",
    email: "massage@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Vida",
    lastName: "Masažuotoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_11",
    email: "restaurant@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Skanus Maistas UAB",
    companyCode: "305123789",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_12",
    email: "lawyer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Mindaugas",
    lastName: "Teisininkas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_13",
    email: "trainer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Eglė",
    lastName: "Trenerė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_14",
    email: "gintpazn@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Agrovartai, UAB",
    companyCode: "305000014",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_15",
    email: "info@absautoservisas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ABS AUTOSERVISAS, UAB",
    companyCode: "305000015",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_16",
    email: "info@acura.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Acura, UAB",
    companyCode: "305000016",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_17",
    email: "ajelectronics1@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AJ Electronics, UAB",
    companyCode: "305000017",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_18",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000018",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_19",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000019",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_20",
    email: "aswobaltic@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ASWO Baltic, UAB",
    companyCode: "305000020",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_21",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000021",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_22",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000022",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_23",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000023",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_24",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000024",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_25",
    email: "gintaras@autoga.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoga, UAB",
    companyCode: "305000025",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_26",
    email: "autolora@autolora.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autolora, UAB",
    companyCode: "305000026",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_27",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000027",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_28",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000028",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_29",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000029",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_30",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000030",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_31",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000031",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_32",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000032",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_33",
    email: "gintpazn@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Agrovartai, UAB",
    companyCode: "305000033",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_34",
    email: "info@absautoservisas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ABS AUTOSERVISAS, UAB",
    companyCode: "305000034",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_35",
    email: "info@acura.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Acura, UAB",
    companyCode: "305000035",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_36",
    email: "ajelectronics1@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AJ Electronics, UAB",
    companyCode: "305000036",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_37",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000037",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_38",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000038",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_39",
    email: "aswobaltic@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ASWO Baltic, UAB",
    companyCode: "305000039",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_40",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000040",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_41",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000041",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_42",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000042",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_43",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000043",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_44",
    email: "gintaras@autoga.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoga, UAB",
    companyCode: "305000044",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_45",
    email: "autolora@autolora.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autolora, UAB",
    companyCode: "305000045",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_46",
    email: "labas@smartrent.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aušra kelyje, MB",
    companyCode: "305000046",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_47",
    email: "info@atntravel.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Mikroautobusų nuoma Vilniuje, UAB",
    companyCode: "305000047",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_48",
    email: "info@uzuojauta.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Užuojauta, UAB",
    companyCode: "305000048",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_49",
    email: "sigis@kaunas.omnitel.net",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "A ir S, kelionių agentūra, S. Jasinskio komercijos įmonė",
    companyCode: "305000049",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_50",
    email: "a9vilnius@b4net.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "A9 Vilnius, UAB",
    companyCode: "305000050",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_51",
    email: "vezipats@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aeromobilis, UAB",
    companyCode: "305000051",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_52",
    email: "aidarent@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AIDA Rent, UAB",
    companyCode: "305000052",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_53",
    email: "info@aldova.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aldova, UAB",
    companyCode: "305000053",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_54",
    email: "info@aautobusai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Algimanto autobusai, UAB",
    companyCode: "305000054",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_55",
    email: "alrodis.uab@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alrodis, UAB",
    companyCode: "305000055",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_56",
    email: "info@alvaturas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alvaturas, UAB",
    companyCode: "305000056",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_57",
    email: "amziausvartai@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AMŽIAUS VARTAI, UAB",
    companyCode: "305000057",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_58",
    email: "info@arselina.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Arselina, UAB",
    companyCode: "305000058",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_59",
    email: "info@keskosenukai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Kesko Senukai Lithuania, UAB",
    companyCode: "305000059",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_60",
    email: "info@savinge.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Savingė, UAB",
    companyCode: "305000060",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_61",
    email: "gintas.p@remo.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Agropaslauga, ŽŪB",
    companyCode: "305000061",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_62",
    email: "info@airbag.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AIRBAG LT, UAB",
    companyCode: "305000062",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_63",
    email: "info@berner.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Albert Berner, UAB",
    companyCode: "305000063",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_64",
    email: "info@alistera.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alistera, UAB",
    companyCode: "305000064",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_65",
    email: "info@aljuva.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Aljuva, UAB",
    companyCode: "305000065",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_66",
    email: "alprofas@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alprofas, UAB",
    companyCode: "305000066",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_67",
    email: "info@alchemija.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Alytaus chemija, AB",
    companyCode: "305000067",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_68",
    email: "info@anda.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Anda, UAB",
    companyCode: "305000068",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_69",
    email: "info@aroste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Arostė, UAB",
    companyCode: "305000069",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_70",
    email: "arsada13@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Arsada, UAB",
    companyCode: "305000070",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_71",
    email: "info@fortius.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Fortius, UAB",
    companyCode: "305000071",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_72",
    email: "info@rataibatai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autobatai, IĮ",
    companyCode: "305000072",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_73",
    email: "info@zemtiekimas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Biržų žemtiekimas, UAB",
    companyCode: "305000073",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_74",
    email: "dagmita@dagmita.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Dagmita, UAB",
    companyCode: "305000074",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_75",
    email: "info@daraida.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Daraida, UAB",
    companyCode: "305000075",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_76",
    email: "info@evaking.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "EVA King, UAB",
    companyCode: "305000076",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_77",
    email: "info@evauto.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Evauto.lt, MB",
    companyCode: "305000077",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_78",
    email: "Dovile.Kazielaite@Bilsteingroup.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ferdinand Bilstein, UAB",
    companyCode: "305000078",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_79",
    email: "help@rrr.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ovoko, UAB",
    companyCode: "305000079",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_80",
    email: "info@pirkitpadangas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ratneta, MB padangos internetu pigiau",
    companyCode: "305000080",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_81",
    email: "info@remparta.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Remparta, UAB automobilių kėbulo dalys",
    companyCode: "305000081",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_82",
    email: "info@padangostau.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Skubas trade, MB",
    companyCode: "305000082",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_83",
    email: "fliquingtl@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Srotas24, UAB Leksvita",
    companyCode: "305000083",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_84",
    email: "agautocentras@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: '"AG" AUTOCENTRAS, UAB',
    companyCode: "305000084",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_85",
    email: "dvart_pijus@yahoo.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "101 garažas, MB",
    companyCode: "305000085",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_86",
    email: "donatas1010@yahoo.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "189 servisai, MB",
    companyCode: "305000086",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_87",
    email: "info@smdalys.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "4 šviesos, MB",
    companyCode: "305000087",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_88",
    email: "info@4x4service.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "4x4 service, UAB",
    companyCode: "305000088",
    createdAt: new Date().toISOString(),
  },
]

const specialistProfiles: SpecialistProfile[] = [
  // Akumuliatorių įmonės
  {
    userId: "user_14",
    type: "business",
    profession: "Automobilių akumuliatoriai",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000001",
    description: "Agrovartai, UAB - automobilių akumuliatorių pardavimas ir aptarnavimas Kauno rajone.",
    services: ["Akumuliatoriai"],
    hourlyRate: 35,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_15",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000002",
    description: "ABS AUTOSERVISAS, UAB - profesionalus automobilių servisas su akumuliatorių paslaugomis Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_16",
    type: "business",
    profession: "Automobilių elektronika",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000003",
    description: "Acura, UAB - automobilių elektronikos ir akumuliatorių specialistai Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 45,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_17",
    type: "business",
    profession: "Automobilių elektronika",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37037000004",
    description: "AJ Electronics, UAB - automobilių elektronikos sprendimai ir akumuliatoriai Rokiškyje/Panevėžyje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 42,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_18",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000005",
    description: "AKSTĖ-servisas, UAB - pilnas automobilių aptarnavimas su akumuliatorių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 38,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_19",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37037000006",
    description: "ARV SERVICE, UAB - automobilių servisas specializuojantis akumuliatorių srityje Panevėžyje.",
    services: ["Akumuliatoriai", "Autokosmetika"],
    hourlyRate: 36,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_20",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000007",
    description: "ASWO Baltic, UAB - Baltijos šalių automobilių servisas su akumuliatorių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_21",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000008",
    description: "Ausegra, UAB - automobilių dalių pardavimas ir akumuliatorių aptarnavimas Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 33,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_22",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000009",
    description: "Auto Aves, UAB - automobilių servisas su akumuliatorių ir dalių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 37,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_23",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000010",
    description: "Autoaibė, UAB - automobilių servisas specializuojantis akumuliatorių srityje Klaipėdoje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 39,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_24",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000011",
    description: "Autodalykai, MB - automobilių servisas su akumuliatorių paslaugomis Kaune.",
    services: ["Akumuliatoriai"],
    hourlyRate: 34,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_25",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000012",
    description: "Autoga, UAB - automobilių servisas su akumuliatorių paslaugomis Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 41,
    experience: 13,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_26",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000013",
    description: "Autolora, UAB - automobilių servisas su akumuliatorių paslaugomis Vilniuje.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  // Autobusų ir mikroautobusų nuomos įmonės
  {
    userId: "user_46",
    type: "business",
    profession: "Mikroautobusų nuoma",
    categories: ["Automobiliai, transportas"],
    locations: ["Šiauliai"], // Telšių r. -> Šiauliai apskritis
    phone: "+37037000046",
    description: "Aušra kelyje, MB - mikroautobusų nuomos paslaugos Telšių rajone.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 45,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_47",
    type: "business",
    profession: "Mikroautobusų nuoma",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000047",
    description: "Mikroautobusų nuoma Vilniuje, UAB - mikroautobusų nuomos paslaugos Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 40,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_48",
    type: "business",
    profession: "Laidojimo paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000048",
    description: "Užuojauta, UAB - laidojimo paslaugos ir transporto organizavimas Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 42,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_49",
    type: "business",
    profession: "Kelionių organizavimas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000049",
    description: "A ir S, kelionių agentūra - kelionių organizavimas ir autobusų nuoma Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 38,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_50",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000050",
    description: "A9 Vilnius, UAB - transporto paslaugos ir autobusų nuoma Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 44,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_51",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000051",
    description: "Aeromobilis, UAB - transporto paslaugos ir mikroautobusų nuoma Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 41,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_52",
    type: "business",
    profession: "Automobilių nuoma",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000052",
    description: "AIDA Rent, UAB - automobilių ir mikroautobusų nuomos paslaugos Vilniuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 39,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_53",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000053",
    description: "Aldova, UAB - transporto paslaugos ir autobusų nuoma Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 43,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_54",
    type: "business",
    profession: "Autobusų paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000054",
    description: "Algimanto autobusai, UAB - autobusų nuomos paslaugos Kaune.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 46,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_55",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Alytus"],
    phone: "+37037000055",
    description: "Alrodis, UAB - transporto paslaugos ir autobusų nuoma Alytuje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 37,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_56",
    type: "business",
    profession: "Turizmo paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000056",
    description: "Alvaturas, UAB - turizmo paslaugos ir autobusų nuoma Neringoje/Klaipėdoje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 48,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_57",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000057",
    description: "AMŽIAUS VARTAI, UAB - transporto paslaugos ir autobusų nuoma Klaipėdoje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 40,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_58",
    type: "business",
    profession: "Transporto paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Jonava"],
    phone: "+37037000058",
    description: "Arselina, UAB - transporto paslaugos ir mikroautobusų nuoma Jonavoje.",
    services: ["Autobusų, mikroautobusų nuoma"],
    hourlyRate: 36,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  // Autokosmetika companies
  {
    userId: "user_59",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000059",
    description: "Kesko Senukai Lithuania, UAB - autokosmetikos prekių pardavimas Kaune.",
    services: ["Autokosmetika"],
    hourlyRate: 30,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_60",
    type: "business",
    profession: "Autokosmetikos paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000060",
    description: "Savingė, UAB - autokosmetikos paslaugos Kaišiadorių rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 25,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_61",
    type: "business",
    profession: "Žemės ūkio paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000061",
    description: "Agropaslauga, ŽŪB - žemės ūkio ir autokosmetikos paslaugos Kaišiadorių rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 28,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_62",
    type: "business",
    profession: "Automobilių saugos sistemos",
    categories: ["Automobiliai, transportas"],
    locations: ["Šakiai"],
    phone: "+37037000062",
    description: "AIRBAG LT, UAB - automobilių saugos sistemų ir autokosmetikos paslaugos Šakiuose.",
    services: ["Autokosmetika"],
    hourlyRate: 35,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_63",
    type: "business",
    profession: "Chemijos produktai",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000063",
    description: "Albert Berner, UAB - chemijos produktų ir autokosmetikos prekių pardavimas Vilniuje.",
    services: ["Autokosmetika"],
    hourlyRate: 40,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_64",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000064",
    description: "Alistera, UAB - autokosmetikos prekių pardavimas Vilniuje.",
    services: ["Autokosmetika"],
    hourlyRate: 32,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_65",
    type: "business",
    profession: "Autokosmetikos paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Utena"],
    phone: "+37037000065",
    description: "Aljuva, UAB - autokosmetikos paslaugos Ukmergėje.",
    services: ["Autokosmetika"],
    hourlyRate: 27,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_66",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000066",
    description: "Alprofas, UAB - autokosmetikos prekių pardavimas Kaune.",
    services: ["Autokosmetika"],
    hourlyRate: 33,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_67",
    type: "business",
    profession: "Chemijos produktai",
    categories: ["Automobiliai, transportas"],
    locations: ["Alytus"],
    phone: "+37037000067",
    description: "Alytaus chemija, AB - chemijos produktų ir autokosmetikos gamyba Alytuje.",
    services: ["Autokosmetika"],
    hourlyRate: 38,
    experience: 20,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_68",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000068",
    description: "Anda, UAB - autokosmetikos prekių pardavimas Kaune.",
    services: ["Autokosmetika"],
    hourlyRate: 29,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_69",
    type: "business",
    profession: "Autokosmetikos paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000069",
    description: "Arostė, UAB - autokosmetikos paslaugos Kaišiadorių rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 26,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_70",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000070",
    description: "Arsada, UAB - autokosmetikos prekių pardavimas Vilniaus rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 31,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  // Autokosmetika companies
  {
    userId: "user_59",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000059",
    description: "Kesko Senukai Lithuania, UAB - autokosmetikos prekių pardavimas Kaune.",
    services: ["Autokosmetika"],
    hourlyRate: 30,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_60",
    type: "business",
    profession: "Autokosmetikos paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000060",
    description: "Savingė, UAB - autokosmetikos paslaugos Kaišiadorių rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 25,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_61",
    type: "business",
    profession: "Žemės ūkio paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000061",
    description: "Agropaslauga, ŽŪB - žemės ūkio ir autokosmetikos paslaugos Kaišiadorių rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 28,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_62",
    type: "business",
    profession: "Automobilių saugos sistemos",
    categories: ["Automobiliai, transportas"],
    locations: ["Šakiai"],
    phone: "+37037000062",
    description: "AIRBAG LT, UAB - automobilių saugos sistemų ir autokosmetikos paslaugos Šakiuose.",
    services: ["Autokosmetika"],
    hourlyRate: 35,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_63",
    type: "business",
    profession: "Chemijos produktai",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000063",
    description: "Albert Berner, UAB - chemijos produktų ir autokosmetikos prekių pardavimas Vilniuje.",
    services: ["Autokosmetika"],
    hourlyRate: 40,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_64",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000064",
    description: "Alistera, UAB - autokosmetikos prekių pardavimas Vilniuje.",
    services: ["Autokosmetika"],
    hourlyRate: 32,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_65",
    type: "business",
    profession: "Autokosmetikos paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Utena"],
    phone: "+37037000065",
    description: "Aljuva, UAB - autokosmetikos paslaugos Ukmergėje.",
    services: ["Autokosmetika"],
    hourlyRate: 27,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_66",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000066",
    description: "Alprofas, UAB - autokosmetikos prekių pardavimas Kaune.",
    services: ["Autokosmetika"],
    hourlyRate: 33,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_67",
    type: "business",
    profession: "Chemijos produktai",
    categories: ["Automobiliai, transportas"],
    locations: ["Alytus"],
    phone: "+37037000067",
    description: "Alytaus chemija, AB - chemijos produktų ir autokosmetikos gamyba Alytuje.",
    services: ["Autokosmetika"],
    hourlyRate: 38,
    experience: 20,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_68",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000068",
    description: "Anda, UAB - autokosmetikos prekių pardavimas Kaune.",
    services: ["Autokosmetika"],
    hourlyRate: 29,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_69",
    type: "business",
    profession: "Autokosmetikos paslaugos",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000069",
    description: "Arostė, UAB - autokosmetikos paslaugos Kaišiadorių rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 26,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_70",
    type: "business",
    profession: "Autokosmetikos prekės",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000070",
    description: "Arsada, UAB - autokosmetikos prekių pardavimas Vilniaus rajone.",
    services: ["Autokosmetika"],
    hourlyRate: 31,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  // Automobilių dalys companies (user_71 to user_88)
  {
    userId: "user_71",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000071",
    description: "Fortius, UAB - automobilių dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 35,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_72",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37037000072",
    description: "Autobatai, IĮ - automobilių dalių pardavimas Klaipėdoje.",
    services: ["Automobilių dalys"],
    hourlyRate: 32,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_73",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37037000073",
    description: "Biržų žemtiekimas, UAB - automobilių dalių pardavimas Biržų rajone.",
    services: ["Automobilių dalys"],
    hourlyRate: 30,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_74",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000074",
    description: "Dagmita, UAB - automobilių dalių pardavimas Kaune.",
    services: ["Automobilių dalys"],
    hourlyRate: 38,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_75",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000075",
    description: "Daraida, UAB - automobilių dalių pardavimas Kaune.",
    services: ["Automobilių dalys"],
    hourlyRate: 36,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_76",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000076",
    description: "EVA King, UAB - automobilių dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 40,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_77",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000077",
    description: "Evauto.lt, MB - automobilių dalių pardavimas internetu Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 34,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_78",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000078",
    description: "Ferdinand Bilstein, UAB - aukštos kokybės automobilių dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 45,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_79",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000079",
    description: "Ovoko, UAB - automobilių dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 33,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_80",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000080",
    description: "Ratneta, MB - padangų pardavimas internetu Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 28,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_81",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000081",
    description: "Remparta, UAB - automobilių kėbulo dalių pardavimas Kaune.",
    services: ["Automobilių dalys"],
    hourlyRate: 37,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_82",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000082",
    description: "Skubas trade, MB - padangų pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 29,
    experience: 4,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_83",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000083",
    description: "Srotas24, UAB Leksvita - automobilių dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 31,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_84",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Šiauliai"],
    phone: "+37037000084",
    description: '"AG" AUTOCENTRAS, UAB - automobilių dalių pardavimas Šiauliuose.',
    services: ["Automobilių dalys"],
    hourlyRate: 35,
    experience: 13,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_85",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37037000085",
    description: "101 garažas, MB - automobilių dalių pardavimas Kaune.",
    services: ["Automobilių dalys"],
    hourlyRate: 27,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_86",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37037000086",
    description: "189 servisai, MB - automobilių dalių pardavimas Panevėžyje.",
    services: ["Automobilių dalys"],
    hourlyRate: 30,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_87",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000087",
    description: "4 šviesos, MB - automobilių šviesos dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 32,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_88",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37037000088",
    description: "4x4 service, UAB - visureigių automobilių dalių pardavimas Vilniuje.",
    services: ["Automobilių dalys"],
    hourlyRate: 42,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
]

// --- DATABASE ACCESS LAYER ---
export const db = {
  users: {
    async findByEmail(email: string): Promise<User | undefined> {
      return users.find((u) => u.email.toLowerCase() === email.toLowerCase())
    },
    async create(data: Omit<User, "id" | "createdAt" | "passwordHash"> & { password?: string }): Promise<User> {
      const newUser: User = {
        id: `user_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        ...data,
        passwordHash: MOCK_PASSWORD_HASH, // In real app: await bcrypt.hash(data.password, 10)
        createdAt: new Date().toISOString(),
      }
      users.push(newUser)
      return newUser
    },
  },
  specialists: {
    async getAll() {
      // Join user and specialist data
      return specialistProfiles.map((profile) => {
        const user = users.find((u) => u.id === profile.userId)
        return {
          ...profile,
          email: user?.email,
          firstName: user?.firstName,
          lastName: user?.lastName,
          companyName: user?.companyName,
          companyCode: user?.companyCode,
        }
      })
    },
    async createProfile(
      data: Omit<SpecialistProfile, "verified" | "image" | "hourlyRate" | "experience">,
    ): Promise<SpecialistProfile> {
      const newProfile: SpecialistProfile = {
        ...data,
        hourlyRate: 25, // Default hourly rate
        experience: 1, // Default experience
        verified: false, // Verification would be a separate process
        image: "/placeholder.svg?height=200&width=200",
      }
      specialistProfiles.push(newProfile)
      return newProfile
    },
    async updateProfile(userId: string, updates: Partial<SpecialistProfile>): Promise<SpecialistProfile | null> {
      const profileIndex = specialistProfiles.findIndex((p) => p.userId === userId)
      if (profileIndex === -1) return null

      specialistProfiles[profileIndex] = { ...specialistProfiles[profileIndex], ...updates }
      return specialistProfiles[profileIndex]
    },
    async getByUserId(userId: string): Promise<SpecialistProfile | undefined> {
      return specialistProfiles.find((p) => p.userId === userId)
    },
  },
  // Mock password comparison
  async comparePassword(password: string, hash: string): Promise<boolean> {
    // In a real app: return await bcrypt.compare(password, hash)
    return password.length > 0 && hash === MOCK_PASSWORD_HASH
  },
}

// This is the type that will be returned from the joined query
export type FullSpecialistProfile = Awaited<ReturnType<typeof db.specialists.getAll>>[0]