// --- MOCK PASSWORD HASHING ---
// In a real app, use a library like bcrypt
const MOCK_PASSWORD_HASH = "$2b$10$fakerakefakerakefakerakeu3eP5wL3/URo2Z.Y5G.x3.g8T9u.1234"

// --- INTERFACES ---
export interface User {
  id: string
  email: string
  passwordHash: string
  role: "customer" | "individual_specialist" | "business_specialist"
  firstName?: string
  lastName?: string
  companyName?: string
  companyCode?: string
  createdAt: string
}

export interface SpecialistProfile {
  userId: string
  profession: string
  categories: string[] // Changed from category to categories (array)
  locations: string[] // Changed from location to locations (array)
  phone: string
  description: string
  services: string[]
  hourlyRate?: number
  experience?: number
  verified: boolean
  image: string
  type: "individual" | "business"
}

// --- PREDEFINED SERVICES ---
// Universal service categories for all specialists
export const serviceCategories = {
  "Automobiliai, transportas": [
    "Akumuliatoriai",
    "Autobusų, mikroautobusų nuoma",
    "Autokosmetika",
    "Automobilių dalys",
    "Automobilių garso ir apsaugos sistemos",
    "Automobilių nuoma",
    "Automobilių parkavimas",
    "Automobilių pervežimas",
    "Automobilių plovyklos",
    "Automobilių prekyba",
    "Automobilių remontas",
    "Automobilių stiklai",
    "Automobilių šaldymo įranga",
    "Automobilių techninė apžiūra",
    "Autosavartynas, naudotos dalys",
    "Autoservisai",
    "Autoservisų, plovyklų, degalinių įranga",
    "Dviračiai",
    "Dviračiai, paspirtukai",
    "Ekspedijavimas",
    "Geležinkelių transportas",
    "Logistikos paslaugos",
    "Motociklai",
    "Oro transportas, aviacija",
    "Padangos, ratlankiai",
    "Pagalba kelyje",
    "Sunkvežimių pardavimas, dalys, remontas",
    "Tepalai, alyvos",
    "Transporto paslaugos",
    "Vandens transportas",
  ],
  "Energetika, žaliavos, kuras": [
    "Antrines žaliavos",
    "Atliekų tvarkymas",
    "Energetika",
    "Gamtos apsauga",
    "Kuras šildymui, malkos, breket...",
    "Kuras, naftos produktai, degal...",
    "Metalų pardavimas, supirkimas",
    "Naudingosios iškasenos",
  ],
  "Finansai, teisė, draudimas": [
    "Antstoliai",
    "Apskaita",
    "Auditas",
    "Bankai, bankinės operacijos",
    "Buhalterinė apskaita",
    "Draudimas",
    "Finansai",
    "Greitieji kreditai, paskolos",
    "Investicinė veikla",
    "Konsultacijų paslaugos",
    "Notarų biurai",
    "Skolų išieškojimas",
    "Tarpininkavimas",
    "Teisinės paslaugos",
    "Teisėtvarka",
    "Turto vertinimas",
  ],
  "Kompiuteriai, IT technologijos": [
    "Interneto paslaugos",
    "Interneto svetainių kūrimas, tvarkymas",
    "Kompiuteriai ir programinė įranga",
    "Kompiuterių remontas, IT paslaugos",
    "Programinės įrangos kūrimas",
    "Telekomunikacijos, ryšio priemonės",
  ],
  "Laisvalaikis, pramogos, turizmas": [
    "Kaimo turizmas",
    "Kavinės, klubai, barai, restoranai",
    "Kelionės",
    "Kino paslaugos",
    "Kultūros centrai",
    "Muziejai",
    "Pirtys ir baseinai",
    "Poilsio namai, sanatorijos",
    "Pramogos ir poilsis",
    "Renginių organizavimas",
    "Sporto paslaugos, sporto klubai",
    "Sveikatingumo, SPA centrai",
    "Teatrai",
    "Viešbučiai, moteliai",
  ],
  "Maisto produktai, gėrimai, prekyba": [
    "Gėrimai (alkoholiniai)",
    "Gėrimai (nealkoholiniai)",
    "Kava, arbata",
    "Kepyklos",
    "Konditerija, saldumynai",
    "Maisto gamyba",
    "Maisto parduotuvės",
    "Maisto produktai",
    "Mėsos perdirbimas, mėsos produktai",
    "Naminiai gyvūnai, maistas, reikmenys",
    "Pienas, pieno produktai",
    "Šaldyti maisto produktai",
    "Šviežį produktai",
  ],
  "Medicina, sveikata, farmacija": [
    "Akušeriai, ginekologai",
    "Estetinė medicina",
    "Globos, rūpybos įstaigos, socialiniai darbuotojai",
    "Greitoji medicinos pagalba",
    "Medicininė įranga",
    "Medicininiai tyrimai, laboratorijos",
    "Medicinos įstaigos",
    "Odontologija, paslaugos",
    "Optika, akiniai",
    "Plastinė, estetinė chirurgija",
    "Privačios gydymo įstaigos",
    "Psichologai, psichoterapeutai",
    "Sanatorijos, reabilitacijos centrai",
    "Vaistai, medicinos medžiagos",
    "Veterinarija",
    "Visuomenės sveikatos priežiūra",
  ],
  "Paslaugos": [
    "Apsaugos sistemos, prietaisai",
    "Apželdimimas ir aplinkos tvarkymas",
    "Avarinės tarnybos",
    "Butities paslaugos",
    "Darbo paieška, tarpinimas",
    "Darbo sauga",
    "Drabužinės",
    "Fotografijos paslaugos, įranga",
    "Grožio salonai, kirpyklos",
    "Imonių steigimas",
    "Individuali veikla",
    "Informacijos teikimas",
    "Keleivių pervežimas",
    "Kenkėjų naikinimas, dezinfekcija",
    "Kita veikla",
    "Komunalinės paslaugos",
    "Laidojimo paslaugos, kremavimas",
    "Laikrodžiai",
    "Lombardi",
    "Maistas į namus, biurą",
    "Paminklai, antkapiai, kapų priežiūra",
    "Parodos, mugės",
    "Paštų administravimas",
    "Patalpų nuoma",
    "Patentinės paslaugos",
    "Perkraustymas",
    "Personalo atranka",
    "Priesagarine sauga, sistemos",
    "Reklamos paslaugos",
    "Saugos tarnybos",
    "Siuvimas, medžiagos",
    "Švaros, valymo paslaugos",
    "Taksi paslaugos",
    "Tarpininkavimas",
    "Vertimas",
    "Vertimo paslaugos",
    "Vestuviniai drabužiai",
    "Video ir audio aparatūra, paslaugos",
    "Video ir audio įrašai",
  ],
  "Pramonė, gamyba, įranga": [
    "Automatizavimas, automatika",
    "Baldai (gamyba)",
    "Chemijos pramonė, gaminiai",
    "Dujos, dujų įranga",
    "Elektros dalys ir įranga",
    "Elektros varikliai",
    "Gamyba",
    "Guoliai",
    "Hidraulika, pneumatika",
    "Kompresoriai, siurbliai",
    "Komunalinė technika",
    "Krautuvai, keltuvai, liftai",
    "Laboratorijos įranga",
    "Laivų remontas, statyba",
    "Maisto gamybos ir perdirbimo įranga",
    "Matavimo prietaisai",
    "Medienos apdirbimas, gaminiai",
    "Metalo apdirbimas, gaminiai",
    "Metalo konstrukcijos, aparatai",
    "Plastikai, guma, jų gaminiai",
    "Plovyklų, autoservisų, degalinių įranga",
    "Pramonės įrengimai",
    "Prekybos įranga",
    "Restoranų, kavinių, barų įranga",
    "Sandėliavimas",
    "Sertifikavimo paslaugos",
    "Šildymas, įrenginiai",
    "Suvirinimas ir suvirinimo aparatūra",
    "Tara, pakuotės",
    "Technologinė įranga",
    "Tyrimai, ekspertizės",
  ],
  "Prekės, prekyba": [
    "Apranga, drabužiai",
    "Audinio, patalynė",
    "Avalynė, batai",
    "Avarinės tarnybos",
    "Baldai (prekyba)",
    "Baldų gamybos medžiagos, furnitūra",
    "Biuro įranga",
    "Buitinė technika",
    "Darbo apranga",
    "Didmeninė prekyba",
    "Dovanos",
    "Durys, raktai, spynos",
    "Eksportas",
    "Elektros montavimo medžiagos",
    "Fejerverkai, pirotechnika",
    "Galanerija, tekstilė",
    "Gėlės ir dekoratyviniai augalai",
    "Ginklai, savisaugos priemonės",
    "Higienos reikmenys",
    "Importas",
    "Indai, valymo įrankiai",
    "Interneto parduotuvės",
    "Juvelyriniai dirbiniai ir bižuterija",
    "Kailiai ir jų dirbiniai",
    "Kanceliarijos prekės",
    "Keramikos gaminiai",
    "Kosmetika, parfumerija",
    "Mažmeninė prekyba",
    "Meno salonai ir galerijos, dailės reikmenys",
    "Muzikos instrumentai",
    "Odos apdirbimas, gaminiai",
    "Pardavimo automatai",
    "Popierius, jo gaminiai",
    "Priesagrinė sauga, sistemos",
    "Sendaikčiai, antikvariatas",
    "Sporto, turizmo reikmenys",
    "Stiklas ir jo gaminiai",
    "Sviesos sistemos, šviestuvai",
    "Tabakas",
    "Tabako gaminiai",
    "Turgavietės",
    "Ūkio prekės",
    "Vaikų prekės",
    "Vaizdo stebėjimo sistemos",
    "Valymo priemonės",
    "Vestuviniai drabužiai",
    "Žaislai",
    "Žaliuzės, užuolaidos, roletai",
    "Žūklės ir medžioklės reikmenys",
  ],
  "Reklama, leidyba": [
    "Grafika, dizainas",
    "Reklamos paslaugos",
    "SEO paslaugos",
    "Spauda, laikraščiai, žurnalai",
    "Spaustuves, leidyba",
    "Televizija ir radijas",
  ],
  "Statyba, remontas, medžiagos, NT": [
    "Akmens gaminiai",
    "Architektai",
    "Aukštalpių paslaugos",
    "Betonas ir jo gaminiai",
    "Dažai, lakai",
    "Elektros instaliacijos darbai",
    "Fasadas, fasado apdaila",
    "Geodezija, kartografija",
    "Geologija",
    "Grindys, grindų dangos",
    "Griovimas, grėžimas",
    "Inžineriniai tinklai ir sistemos",
    "Interjero apdailos medžiagos",
    "Įrankiai",
    "Kelių tiesimas, remontas, tiltas",
    "Langai, durys",
    "Mediena, jos gaminiai",
    "Melioracija, melioracijos technika",
    "Namų statyba",
    "Nekilnojamasis turtas",
    "Patalpų nuoma",
    "Projektavimas",
    "Santechnika",
    "Sienos, lubos",
    "Šildymas, įrenginiai",
    "Šiltinimas, renovacija",
    "Statyba",
    "Statybinės medžiagos",
    "Statyba, renovacija",
    "Statybos technika, įranga, nuoma",
    "Stogų dangos, paslaugos",
    "Tvirtinimo detalės, elementai",
    "Vandentiekis, nuotekos, vamzdynai",
    "Vartai, tvoros",
    "Ventiliacija, kondicionavimas",
    "Žemetvarka",
    "Židiniai, krosnys",
  ],
  "Švietimas, ugdymas, kultūra": [
    "Aukštosios mokyklos, universitetas",
    "Bibliotekos, archyvavimo paslaugos",
    "Institutai, moksliniai tyrimai",
    "Kalbų kursai",
    "Knygos ir knygynai",
    "Meno mokymo įstaigos",
    "Mokyklos, gimnazijos",
    "Mokymo centrai, kursai",
    "Mokymo kursai",
    "Profesinio mokymo įstaigos",
    "Vaikų būreliai",
    "Vaikų darželiai",
    "Vairavimo mokymas",
  ],
  "Valstybinės įstaigos, organizacijos": [
    "Bendruomenės",
    "Globa ir priežiūra",
    "Gyvūnų globa",
    "Kontrolės tarnybos",
    "Labdara, parama",
    "Muitinių paslaugos, muitinės",
    "Namų savininkų bendrijos",
    "Politinės organizacijos",
    "Religinės organizacijos",
    "Savivaldybės",
    "Sąjungos, fondai, asociacijos",
    "Seimynos",
    "Senūnijos",
    "Socialinės paslaugos",
    "Sodininkų bendrijos",
    "Sporto organizacijos",
    "Valstybinės institucijos",
  ],
  "Žemės ūkis, agrotechnika": [
    "Augalininkystė, sodininkystė",
    "Daržininkystė, sodininkystė",
    "Grūdininkystė",
    "Gyvulininkystė, veislininkystė",
    "Miškininkystė",
    "Miško gėrybės",
    "Miško, sodo, vejos technika",
    "Pašarai, gyvulinis maistas",
    "Trąšos",
    "Vaisiai",
    "Žemes ūkio technika",
    "Žemės ūkis, paslaugos",
    "Žuvininkystė",
    "Žuvininkystė, žuvies produktai",
    "Žverininkystė",
  ],
}

// Export predefinedServices as an alias for serviceCategories
export const predefinedServices = serviceCategories

// Default cities
const defaultCities = [
  "Vilnius",
  "Kaunas",
  "Klaipėda",
  "Šiauliai",
  "Panevėžys",
  "Alytus",
  "Marijampolė",
  "Mažeikiai",
  "Jonava",
  "Utena",
]

// --- MOCK DATABASE ---
const users: User[] = [
  {
    id: "user_1",
    email: "customer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "customer",
    firstName: "Petras",
    lastName: "Klientauskas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_2",
    email: "individual@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Gintarė",
    lastName: "Urbonaitė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_3",
    email: "business@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Petraičio Santechnika MB",
    companyCode: "305123456",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_4",
    email: "programmer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Tomas",
    lastName: "Programauskas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_5",
    email: "itcompany@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "TechSolutions UAB",
    companyCode: "305987654",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_6",
    email: "photographer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Laura",
    lastName: "Fotografė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_7",
    email: "accountant@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Rasa",
    lastName: "Skaičiuotoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_8",
    email: "cleaning@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Švarūs Namai MB",
    companyCode: "305456789",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_9",
    email: "teacher@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Ingrida",
    lastName: "Mokytoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_10",
    email: "massage@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Vida",
    lastName: "Masažuotoja",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_11",
    email: "restaurant@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Skanus Maistas UAB",
    companyCode: "305123789",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_12",
    email: "lawyer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Mindaugas",
    lastName: "Teisininkas",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_13",
    email: "trainer@intouch.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "individual_specialist",
    firstName: "Eglė",
    lastName: "Trenerė",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_14",
    email: "gintpazn@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Agrovartai, UAB",
    companyCode: "305000014",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_15",
    email: "info@absautoservisas.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ABS AUTOSERVISAS, UAB",
    companyCode: "305000015",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_16",
    email: "info@acura.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Acura, UAB",
    companyCode: "305000016",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_17",
    email: "ajelectronics1@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AJ Electronics, UAB",
    companyCode: "305000017",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_18",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000018",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_19",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000019",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_20",
    email: "aswobaltic@gmail.com",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ASWO Baltic, UAB",
    companyCode: "305000020",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_21",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000021",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_22",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000022",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_23",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000023",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_24",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000024",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_25",
    email: "gintaras@autoga.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoga, UAB",
    companyCode: "305000025",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_26",
    email: "autolora@autolora.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autolora, UAB",
    companyCode: "305000026",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_27",
    email: "info@akste.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "AKSTĖ-servisas, UAB",
    companyCode: "305000027",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_28",
    email: "info@arvservice.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "ARV SERVICE, UAB",
    companyCode: "305000028",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_29",
    email: "info@ausegra.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Ausegra, UAB",
    companyCode: "305000029",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_30",
    email: "info@autoaves.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Auto Aves, UAB",
    companyCode: "305000030",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_31",
    email: "info@autoaibe.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autoaibė, UAB",
    companyCode: "305000031",
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_32",
    email: "info@autodalykai.lt",
    passwordHash: MOCK_PASSWORD_HASH,
    role: "business_specialist",
    companyName: "Autodalykai, MB",
    companyCode: "305000032",
    createdAt: new Date().toISOString(),
  },
]

const specialistProfiles: SpecialistProfile[] = [
  {
    userId: "user_2",
    type: "individual",
    profession: "Grafikos dizainerė",
    categories: ["Dizainas/Kūryba"],
    locations: ["Klaipėda"],
    phone: "+37060045678",
    description: "Kūrybinga grafikos dizainerė su 10 metų patirtimi.",
    services: ["Grafikos dizainas", "Logo kūrimas"],
    hourlyRate: 35,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_3",
    type: "business",
    profession: "Santechnikas",
    categories: ["Statyba"],
    locations: ["Vilnius"],
    phone: "+37060012345",
    description: "Profesionalus santechnikas su 8 metų patirtimi.",
    services: ["Renovacijos darbai", "Interjero apdaila"],
    hourlyRate: 25,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_4",
    type: "individual",
    profession: "Programuotojas",
    categories: ["Programavimas/IT"],
    locations: ["Vilnius", "Kaunas"],
    phone: "+37060098765",
    description: "Full-stack programuotojas specializuojantis web aplikacijose.",
    services: ["Web svetainių kūrimas", "Programinės įrangos kūrimas"],
    hourlyRate: 45,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_5",
    type: "business",
    profession: "IT konsultantas",
    categories: ["Technologijos"],
    locations: ["Vilnius"],
    phone: "+37060087654",
    description: "IT konsultacijų įmonė su 15 metų patirtimi rinkoje.",
    services: ["IT konsultacijos", "Programinės įrangos kūrimas"],
    hourlyRate: 60,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_6",
    type: "individual",
    profession: "Fotografė",
    categories: ["Fotografija/Filmavimas"],
    locations: ["Kaunas"],
    phone: "+37060076543",
    description: "Profesionali fotografė specializuojantis vestuvių fotografijoje.",
    services: ["Vestuvių fotografija", "Portretų fotografija"],
    hourlyRate: 40,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_7",
    type: "individual",
    profession: "Buhalterė",
    categories: ["Apskaita/Buhalterija"],
    locations: ["Šiauliai"],
    phone: "+37060065432",
    description: "Patyrusi buhalterė su CPA sertifikatu.",
    services: ["Buhalterinės apskaitos vedimas", "Mokesčių deklaravimas"],
    hourlyRate: 30,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_8",
    type: "business",
    profession: "Valymo paslaugos",
    categories: ["Kita"],
    locations: ["Vilnius", "Kaunas"],
    phone: "+37060054321",
    description: "Profesionalios valymo paslaugos namams ir biurams.",
    services: ["Namų valymas", "Biurų valymas"],
    hourlyRate: 20,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_9",
    type: "individual",
    profession: "Anglų kalbos mokytoja",
    categories: ["Mokymas/Korepetavimas"],
    locations: ["Klaipėda"],
    phone: "+37060043210",
    description: "Anglų kalbos mokytoja su tarptautiniu sertifikatu.",
    services: ["Anglų kalbos pamokos", "Kompiuterinio raštingumo kursai"],
    hourlyRate: 25,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_10",
    type: "individual",
    profession: "Masažuotoja",
    categories: ["Sveikatos priežiūros paslaugos"],
    locations: ["Panevėžys"],
    phone: "+37060032109",
    description: "Licencijuota masažuotoja specializuojantis terapiniame masaže.",
    services: ["Masažas", "Fizioterapija"],
    hourlyRate: 35,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_11",
    type: "business",
    profession: "Restorano paslaugos",
    categories: ["Apgyvendinimas ir maitinimas"],
    locations: ["Vilnius"],
    phone: "+37060021098",
    description: "Aukštos kokybės maitinimo paslaugos renginiams.",
    services: ["Maitinimo paslaugos", "Renginių organizavimas"],
    hourlyRate: 50,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_12",
    type: "individual",
    profession: "Teisės konsultantas",
    categories: ["Teisinės paslaugos"],
    locations: ["Alytus"],
    phone: "+37060010987",
    description: "Teisės konsultantas specializuojantis verslo teisėje.",
    services: ["Teisinės konsultacijos", "Dokumentų rengimas"],
    hourlyRate: 55,
    experience: 14,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_13",
    type: "individual",
    profession: "Fitnes trenerė",
    categories: ["Asmeninis treniravimas"],
    locations: ["Marijampolė"],
    phone: "+37060009876",
    description: "Sertifikuota fitnes trenerė su sporto mokslo išsilavinimu.",
    services: ["Fitnes treneris", "Mitybos plano sudarymas"],
    hourlyRate: 30,
    experience: 5,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_14",
    type: "business",
    profession: "Automobilių akumuliatoriai",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37060000014",
    description: "Automobilių akumuliatorių pardavimas ir aptarnavimas.",
    services: ["Akumuliatoriai"],
    hourlyRate: 40,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_15",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37060000015",
    description: "Profesionalus automobilių servisas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 35,
    experience: 12,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_16",
    type: "business",
    profession: "Automobilių elektronika",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37060000016",
    description: "Automobilių elektronikos ir akumuliatorių specialistai.",
    services: ["Akumuliatoriai", "Automobilių garso ir apsaugos sistemos"],
    hourlyRate: 45,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_17",
    type: "business",
    profession: "Automobilių elektronika",
    categories: ["Automobiliai, transportas"],
    locations: ["Šiauliai"],
    phone: "+37060000017",
    description: "Automobilių elektronikos sprendimai ir akumuliatoriai.",
    services: ["Akumuliatoriai", "Automobilių garso ir apsaugos sistemos"],
    hourlyRate: 42,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_18",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37060000018",
    description: "Pilnas automobilių aptarnavimas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 38,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_19",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37060000019",
    description: "Automobilių servisas specializuojantis akumuliatorių srityje.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 36,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_20",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Alytus"],
    phone: "+37060000020",
    description: "Baltijos šalių automobilių servisas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 40,
    experience: 11,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_21",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Marijampolė"],
    phone: "+37060000021",
    description: "Automobilių dalių pardavimas ir akumuliatorių aptarnavimas.",
    services: ["Akumuliatoriai", "Automobilių dalys"],
    hourlyRate: 33,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_22",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Mažeikiai"],
    phone: "+37060000022",
    description: "Automobilių servisas su akumuliatorių ir dalių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių dalys"],
    hourlyRate: 37,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_23",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Jonava"],
    phone: "+37060000023",
    description: "Automobilių servisas specializuojantis akumuliatorių srityje.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 39,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_24",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Utena"],
    phone: "+37060000024",
    description: "Automobilių servisas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 34,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_25",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37060000025",
    description: "Automobilių servisas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 41,
    experience: 13,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_27",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37060000027",
    description: "Automobilių servisas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 38,
    experience: 15,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_28",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Panevėžys"],
    phone: "+37060000028",
    description: "Automobilių servisas specializuojantis akumuliatorių srityje.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 36,
    experience: 9,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_29",
    type: "business",
    profession: "Automobilių dalys",
    categories: ["Automobiliai, transportas"],
    locations: ["Vilnius"],
    phone: "+37060000029",
    description: "Automobilių dalių pardavimas ir akumuliatorių aptarnavimas.",
    services: ["Akumuliatoriai", "Automobilių dalys"],
    hourlyRate: 33,
    experience: 6,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_30",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37060000030",
    description: "Automobilių servisas su akumuliatorių ir dalių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių dalys"],
    hourlyRate: 37,
    experience: 8,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_31",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Klaipėda"],
    phone: "+37060000031",
    description: "Automobilių servisas specializuojantis akumuliatorių srityje.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 39,
    experience: 10,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    userId: "user_32",
    type: "business",
    profession: "Automobilių servisas",
    categories: ["Automobiliai, transportas"],
    locations: ["Kaunas"],
    phone: "+37060000032",
    description: "Automobilių servisas su akumuliatorių paslaugomis.",
    services: ["Akumuliatoriai", "Automobilių remontas"],
    hourlyRate: 34,
    experience: 7,
    verified: true,
    image: "/placeholder.svg?height=200&width=200",
  },
]

// --- DATABASE ACCESS LAYER ---
export const db = {
  users: {
    async findByEmail(email: string): Promise<User | undefined> {
      return users.find((u) => u.email.toLowerCase() === email.toLowerCase())
    },
    async create(data: Omit<User, "id" | "createdAt" | "passwordHash"> & { password?: string }): Promise<User> {
      const newUser: User = {
        id: `user_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        ...data,
        passwordHash: MOCK_PASSWORD_HASH, // In real app: await bcrypt.hash(data.password, 10)
        createdAt: new Date().toISOString(),
      }
      users.push(newUser)
      return newUser
    },
  },
  specialists: {
    async getAll() {
      // Join user and specialist data
      return specialistProfiles.map((profile) => {
        const user = users.find((u) => u.id === profile.userId)
        return {
          ...profile,
          email: user?.email,
          firstName: user?.firstName,
          lastName: user?.lastName,
          companyName: user?.companyName,
          companyCode: user?.companyCode,
        }
      })
    },
    async createProfile(
      data: Omit<SpecialistProfile, "verified" | "image" | "hourlyRate" | "experience">,
    ): Promise<SpecialistProfile> {
      const newProfile: SpecialistProfile = {
        ...data,
        hourlyRate: 25, // Default hourly rate
        experience: 1, // Default experience
        verified: false, // Verification would be a separate process
        image: "/placeholder.svg?height=200&width=200",
      }
      specialistProfiles.push(newProfile)
      return newProfile
    },
    async updateProfile(userId: string, updates: Partial<SpecialistProfile>): Promise<SpecialistProfile | null> {
      const profileIndex = specialistProfiles.findIndex((p) => p.userId === userId)
      if (profileIndex === -1) return null

      specialistProfiles[profileIndex] = { ...specialistProfiles[profileIndex], ...updates }
      return specialistProfiles[profileIndex]
    },
    async getByUserId(userId: string): Promise<SpecialistProfile | undefined> {
      return specialistProfiles.find((p) => p.userId === userId)
    },
  },
  // Mock password comparison
  async comparePassword(password: string, hash: string): Promise<boolean> {
    // In a real app: return await bcrypt.compare(password, hash)
    return password.length > 0 && hash === MOCK_PASSWORD_HASH
  },
}

// This is the type that will be returned from the joined query
export type FullSpecialistProfile = Awaited<ReturnType<typeof db.specialists.getAll>>[0]